name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Surge
      run: npm install --global surge

    - name: Desplegar a Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: |
        surge ./ --domain https://cdtm0904-pagina.surge.sh --token $SURGE_TOKEN
